using System;

namespace TDengineDriver
{

	internal enum TDengineDataType
	{
		
		TSDB_DATA_TYPE_NULL,
		TSDB_DATA_TYPE_BOOL,
		TSDB_DATA_TYPE_TINYINT,
		TSDB_DATA_TYPE_SMALLINT,
		TSDB_DATA_TYPE_INT,
		TSDB_DATA_TYPE_BIGINT,
		TSDB_DATA_TYPE_FLOAT,
		TSDB_DATA_TYPE_DOUBLE,
		TSDB_DATA_TYPE_BINARY,
		TSDB_DATA_TYPE_TIMESTAMP,
		TSDB_DATA_TYPE_NCHAR,
		TSDB_DATA_TYPE_UTINYINT,
		TSDB_DATA_TYPE_USMALLINT,
		TSDB_DATA_TYPE_UINT,
		TSDB_DATA_TYPE_UBIGINT
	}
}
